In [1]:
import geopandas as gpd

In [6]:
property = gpd.read_file('output/property_ring.gpkg')

property.columns

Index(['GrossSalePrice', 'AgeAtSale', 'LandArea', 'TotalFloorArea',
       'water_DIST', 'bus_DIST', 'Census_Pop', 'RnkIMDNoEm', 'RnkIMDNoIn',
       'RnkIMDNoCr', 'RnkIMDNoHo', 'RnkIMDNoHe', 'RnkIMDNoEd', 'RnkIMDNoAc',
       'DECILE_high', 'DECILE_prim', 'Median_Income', 'CBD_DIST',
       'cycleways_DIST', 'cycle_DENS', 'year_2018', 'year_2019', 'on_DIST',
       'on_DENS', 'canopy_ring_0_20', 'canopy_ring_20_50',
       'canopy_ring_50_100', 'canopy_ring_100_200', 'canopy_density_0_20',
       'canopy_density_20_50', 'canopy_density_50_100',
       'canopy_density_100_200', 'geometry'],
      dtype='object')

In [7]:
property_new = property.reset_index(drop=True)
property_new['property_id'] = property_new.index.astype(int)

In [8]:
property.head()

,GrossSalePrice,AgeAtSale,LandArea,TotalFloorArea,water_DIST,bus_DIST,Census_Pop,RnkIMDNoEm,RnkIMDNoIn,RnkIMDNoCr,...,on_DENS,canopy_ring_0_20,canopy_ring_20_50,canopy_ring_50_100,canopy_ring_100_200,canopy_density_0_20,canopy_density_20_50,canopy_density_50_100,canopy_density_100_200,geometry
0,610000,24,685.0,211.0,189.601703,216.798910,930.0,1811.0,849.0,1231.0,...,2298.6,1.077267,163.500474,1626.122721,10785.446182,0.085726,2.478277,6.901479,11.443714,POINT (1564919.129 5174157.305)
1,477500,42,609.0,120.0,139.581200,154.824709,930.0,1811.0,849.0,1231.0,...,2303.7,20.957896,450.415001,2615.078658,15687.515456,1.667776,6.827217,11.098739,16.644971,POINT (1565047.92 5174178.753)
2,655000,22,704.0,245.0,201.942495,192.941029,930.0,1811.0,849.0,1231.0,...,2288.1,10.299413,144.270775,1962.604434,9604.906243,0.819601,2.186801,8.329552,10.191122,POINT (1564904.931 5174179.536)
3,500000,44,869.0,131.0,157.854014,179.645498,930.0,1811.0,849.0,1231.0,...,2296.0,74.306779,392.823676,2632.706474,16198.513984,5.913146,5.954270,11.173553,17.187157,POINT (1565029.188 5174201.753)
4,880000,22,1149.0,279.0,199.693219,216.730600,930.0,1811.0,849.0,1231.0,...,2291.7,0.000000,279.813206,2358.284666,15006.402033,0.000000,4.241300,10.008871,15.922287,POINT (1564988.184 5174211.698)

In [ ]:
property_new.head()

,GrossSalePrice,AgeAtSale,LandArea,TotalFloorArea,water_DIST,bus_DIST,Census_Pop,RnkIMDNoEm,RnkIMDNoIn,RnkIMDNoCr,...,canopy_ring_0_20,canopy_ring_20_50,canopy_ring_50_100,canopy_ring_100_200,canopy_density_0_20,canopy_density_20_50,canopy_density_50_100,canopy_density_100_200,geometry,property_id
0,610000,24,685.0,211.0,189.601703,216.798910,930.0,1811.0,849.0,1231.0,...,1.077267,163.500474,1626.122721,10785.446182,0.085726,2.478277,6.901479,11.443714,POINT (1564919.129 5174157.305),0
1,477500,42,609.0,120.0,139.581200,154.824709,930.0,1811.0,849.0,1231.0,...,20.957896,450.415001,2615.078658,15687.515456,1.667776,6.827217,11.098739,16.644971,POINT (1565047.92 5174178.753),1
2,655000,22,704.0,245.0,201.942495,192.941029,930.0,1811.0,849.0,1231.0,...,10.299413,144.270775,1962.604434,9604.906243,0.819601,2.186801,8.329552,10.191122,POINT (1564904.931 5174179.536),2
3,500000,44,869.0,131.0,157.854014,179.645498,930.0,1811.0,849.0,1231.0,...,74.306779,392.823676,2632.706474,16198.513984,5.913146,5.954270,11.173553,17.187157,POINT (1565029.188 5174201.753),3
4,880000,22,1149.0,279.0,199.693219,216.730600,930.0,1811.0,849.0,1231.0,...,0.000000,279.813206,2358.284666,15006.402033,0.000000,4.241300,10.008871,15.922287,POINT (1564988.184 5174211.698),4

In [10]:
property_new.to_file('output/property_ring_with_id.gpkg')