In [1]:
import geopandas as gpd
import pandas as pd
from multiprocessing import Pool, cpu_count
from functools import partial
from tqdm import tqdm
import os
from helpers.helpers import (calculate_canopy_for_all_reaches, process_canopy_chunk)
import numpy as np
import os, time

In [2]:
ta = gpd.read_file('data/chc-boundaries/territorial-authority-2021-generalised.gpkg', engine='pyogrio')
sa2 = gpd.read_file('data/chc-boundaries/sa2/statistical-area-2-2023-generalised.shp')
ta_chc = ta[ta['TA2021_V1_00_NAME_ASCII'] == 'Christchurch City']
sa2_chc = gpd.clip(sa2, ta_chc)

canopy = gpd.read_file('data/canopy.gdb')
property_full = gpd.read_file('output/property.gpkg')
access_points = gpd.read_file('output/property_accesspoints.gpkg', engine='pyogrio')

# boundary = sa2_chc[sa2_chc['SA22023__2'].str.lower().str.contains('ilam')]

property = gpd.clip(property_full, sa2_chc)
TARGET_CRS = 2193

/Users/rujalshrestha/Projects/chc-property-prices/venv/lib/python3.13/site-packages/pyogrio/raw.py:198: RuntimeWarning: organizePolygons() received a polygon with more than 100 parts. The processing may be really slow.  You can skip the processing by setting METHOD=SKIP, or only make it analyze counter-clock wise parts by setting METHOD=ONLY_CCW if you can assume that the outline of holes is counter-clock wise defined
  return ogr_read(

In [3]:
property_geom = property[['property_id', 'geometry']].copy()

property_geom = gpd.GeoDataFrame(
  property_geom,
  crs=property.crs,
  geometry="geometry"
)

access_points = access_points.rename(columns={'geometry': 'access_point'})

property_reaches = property_geom.merge(
    access_points[['property_id', 'access_point']],    
    on='property_id',
    how='left'
)

REACHES = [75]
# REACHES = [50, 100, 150, 200, 250, 300, 350, 400]

for distance in REACHES:
  path = f'output/property_reach_{distance}m.gpkg'
  reach_col = f'reach_{distance}m'
  
  if os.path.exists(path):
      reach_gdf = gpd.read_file(path, engine='pyogrio')
      reach_gdf = reach_gdf.rename(columns={'geometry': reach_col})
      
      property_reaches = property_reaches.merge(
          reach_gdf[['property_id', reach_col]],    
          on='property_id',
          how='left'
      )

In [4]:
n_cores = cpu_count()
n_chunks = n_cores * 2

chunks = np.array_split(property_reaches, n_chunks)

/Users/rujalshrestha/Projects/chc-property-prices/venv/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'GeoDataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'GeoDataFrame.transpose' instead.
  return bound(*args, **kwds)
/Users/rujalshrestha/Projects/chc-property-prices/venv/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'GeoDataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'GeoDataFrame.transpose' instead.
  return bound(*args, **kwds)
/Users/rujalshrestha/Projects/chc-property-prices/venv/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'GeoDataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'GeoDataFrame.transpose' instead.
  return bound(*args, **kwds)
/Users/rujalshrestha/Projects/chc-property-prices/venv/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'GeoDataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'GeoDataFrame.transpose' instead.
  return bound(*args, **kwds)
/Users/rujalshrestha/Projects/chc-property-prices/venv/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'GeoDataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'GeoDataFrame.transpose' instead.
  return bound(*args, **kwds)
/Users/rujalshrestha/Projects/chc-property-prices/venv/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'GeoDataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'GeoDataFrame.transpose' instead.
  return bound(*args, **kwds)
/Users/rujalshrestha/Projects/chc-property-prices/venv/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'GeoDataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'GeoDataFrame.transpose' instead.
  return bound(*args, **kwds)
/Users/rujalshrestha/Projects/chc-property-prices/venv/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'GeoDataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'GeoDataFrame.transpose' instead.
  return bound(*args, **kwds)
/Users/rujalshrestha/Projects/chc-property-prices/venv/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'GeoDataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'GeoDataFrame.transpose' instead.
  return bound(*args, **kwds)
/Users/rujalshrestha/Projects/chc-property-prices/venv/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'GeoDataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'GeoDataFrame.transpose' instead.
  return bound(*args, **kwds)
/Users/rujalshrestha/Projects/chc-property-prices/venv/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'GeoDataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'GeoDataFrame.transpose' instead.
  return bound(*args, **kwds)
/Users/rujalshrestha/Projects/chc-property-prices/venv/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'GeoDataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'GeoDataFrame.transpose' instead.
  return bound(*args, **kwds)
/Users/rujalshrestha/Projects/chc-property-prices/venv/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'GeoDataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'GeoDataFrame.transpose' instead.
  return bound(*args, **kwds)
/Users/rujalshrestha/Projects/chc-property-prices/venv/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'GeoDataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'GeoDataFrame.transpose' instead.
  return bound(*args, **kwds)
/Users/rujalshrestha/Projects/chc-property-prices/venv/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'GeoDataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'GeoDataFrame.transpose' instead.
  return bound(*args, **kwds)
/Users/rujalshrestha/Projects/chc-property-prices/venv/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'GeoDataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'GeoDataFrame.transpose' instead.
  return bound(*args, **kwds)
/Users/rujalshrestha/Projects/chc-property-prices/venv/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'GeoDataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'GeoDataFrame.transpose' instead.
  return bound(*args, **kwds)
/Users/rujalshrestha/Projects/chc-property-prices/venv/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'GeoDataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'GeoDataFrame.transpose' instead.
  return bound(*args, **kwds)
/Users/rujalshrestha/Projects/chc-property-prices/venv/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'GeoDataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'GeoDataFrame.transpose' instead.
  return bound(*args, **kwds)
/Users/rujalshrestha/Projects/chc-property-prices/venv/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'GeoDataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'GeoDataFrame.transpose' instead.
  return bound(*args, **kwds)
/Users/rujalshrestha/Projects/chc-property-prices/venv/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'GeoDataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'GeoDataFrame.transpose' instead.
  return bound(*args, **kwds)

In [5]:
canopy_sindex = canopy.sindex
reaches = [75]
# reaches = [50, 100, 150, 200, 250, 300, 350, 400]

if __name__ == "__main__":
    with Pool(processes=n_cores) as pool:
        func = partial(
            process_canopy_chunk,
            canopy_gdf=canopy,
            canopy_sindex=canopy_sindex,
            reaches=reaches,
            buffer_dist=10
        )

        results = list(
            tqdm(
                pool.imap(func, chunks),
                total=len(chunks),
                desc="Parallel canopy calculation"
            )
        )

Parallel canopy calculation:   0%|          | 0/20 [00:00<?, ?it/s]

[PID 6530] 20/616 rows | 0.2s elapsed | 111.73 rows/s
[PID 6530] 40/616 rows | 0.3s elapsed | 155.75 rows/s
[PID 6530] 60/616 rows | 0.4s elapsed | 137.03 rows/s
[PID 6530] 80/616 rows | 0.5s elapsed | 158.72 rows/s
[PID 6530] 100/616 rows | 0.6s elapsed | 181.72 rows/s
[PID 6530] 120/616 rows | 0.6s elapsed | 206.15 rows/s
[PID 6530] 140/616 rows | 0.6s elapsed | 233.07 rows/s
[PID 6530] 160/616 rows | 0.6s elapsed | 250.46 rows/s
[PID 6530] 180/616 rows | 0.7s elapsed | 274.88 rows/s
[PID 6530] 200/616 rows | 0.7s elapsed | 292.71 rows/s
[PID 6530] 220/616 rows | 0.7s elapsed | 304.25 rows/s
[PID 6530] 240/616 rows | 0.8s elapsed | 311.83 rows/s
[PID 6530] 260/616 rows | 0.8s elapsed | 318.42 rows/s
[PID 6530] 280/616 rows | 0.9s elapsed | 328.28 rows/s
[PID 6530] 300/616 rows | 0.9s elapsed | 330.84 rows/s
[PID 6530] 320/616 rows | 0.9s elapsed | 346.33 rows/s
[PID 6530] 340/616 rows | 0.9s elapsed | 359.72 rows/s
[PID 6530] 360/616 rows | 1.0s elapsed | 369.22 rows/s
[PID 6530] 380/616 rows | 1.0s elapsed | 383.24 rows/s
[PID 6530] 400/616 rows | 1.0s elapsed | 398.86 rows/s
[PID 6530] 420/616 rows | 1.0s elapsed | 407.71 rows/s
[PID 6530] 440/616 rows | 1.1s elapsed | 417.08 rows/s
[PID 6530] 460/616 rows | 1.1s elapsed | 426.82 rows/s
[PID 6530] 480/616 rows | 1.1s elapsed | 430.22 rows/s
[PID 6530] 500/616 rows | 1.1s elapsed | 436.22 rows/s
[PID 6530] 520/616 rows | 1.2s elapsed | 437.63 rows/s
[PID 6530] 540/616 rows | 1.2s elapsed | 439.23 rows/s
[PID 6530] 560/616 rows | 1.3s elapsed | 443.43 rows/s
[PID 6530] 580/616 rows | 1.3s elapsed | 440.26 rows/s
[PID 6530] 600/616 rows | 1.4s elapsed | 444.24 rows/s
[PID 6530] chunk done in 1.4s

Parallel canopy calculation:   5%|▌         | 1/20 [00:41<13:16, 41.94s/it]

[PID 6531] 20/616 rows | 0.3s elapsed | 73.40 rows/s
[PID 6531] 40/616 rows | 0.4s elapsed | 110.71 rows/s
[PID 6531] 60/616 rows | 0.4s elapsed | 141.39 rows/s
[PID 6531] 80/616 rows | 0.4s elapsed | 180.04 rows/s
[PID 6531] 100/616 rows | 0.5s elapsed | 207.09 rows/s
[PID 6531] 120/616 rows | 0.5s elapsed | 238.62 rows/s
[PID 6531] 140/616 rows | 0.5s elapsed | 266.77 rows/s
[PID 6531] 160/616 rows | 0.5s elapsed | 301.71 rows/s
[PID 6531] 180/616 rows | 0.5s elapsed | 331.06 rows/s
[PID 6531] 200/616 rows | 0.6s elapsed | 355.80 rows/s
[PID 6531] 220/616 rows | 0.6s elapsed | 359.78 rows/s
[PID 6531] 240/616 rows | 0.7s elapsed | 357.98 rows/s
[PID 6531] 260/616 rows | 0.7s elapsed | 366.31 rows/s
[PID 6531] 280/616 rows | 0.8s elapsed | 364.20 rows/s
[PID 6531] 300/616 rows | 0.9s elapsed | 346.63 rows/s
[PID 6531] 320/616 rows | 0.9s elapsed | 359.33 rows/s
[PID 6531] 340/616 rows | 0.9s elapsed | 372.36 rows/s
[PID 6531] 360/616 rows | 0.9s elapsed | 382.74 rows/s
[PID 6531] 380/616 rows | 1.0s elapsed | 397.55 rows/s
[PID 6531] 400/616 rows | 1.0s elapsed | 386.90 rows/s
[PID 6531] 420/616 rows | 1.1s elapsed | 379.54 rows/s
[PID 6531] 440/616 rows | 1.2s elapsed | 378.45 rows/s
[PID 6531] 460/616 rows | 1.2s elapsed | 379.95 rows/s
[PID 6531] 480/616 rows | 1.3s elapsed | 381.48 rows/s
[PID 6531] 500/616 rows | 1.3s elapsed | 380.45 rows/s
[PID 6531] 520/616 rows | 1.4s elapsed | 381.68 rows/s
[PID 6531] 540/616 rows | 1.4s elapsed | 388.87 rows/s
[PID 6531] 560/616 rows | 1.5s elapsed | 384.57 rows/s
[PID 6531] 580/616 rows | 1.5s elapsed | 378.40 rows/s
[PID 6531] 600/616 rows | 1.6s elapsed | 378.22 rows/s
[PID 6531] chunk done in 1.6s

Parallel canopy calculation:  10%|█         | 2/20 [01:34<14:32, 48.44s/it]

[PID 6532] 20/616 rows | 0.2s elapsed | 87.71 rows/s
[PID 6532] 40/616 rows | 0.3s elapsed | 130.24 rows/s
[PID 6532] 60/616 rows | 0.4s elapsed | 157.04 rows/s
[PID 6532] 80/616 rows | 0.5s elapsed | 164.76 rows/s
[PID 6532] 100/616 rows | 0.6s elapsed | 181.72 rows/s
[PID 6532] 120/616 rows | 0.6s elapsed | 197.25 rows/s
[PID 6532] 140/616 rows | 0.7s elapsed | 203.34 rows/s
[PID 6532] 160/616 rows | 0.8s elapsed | 209.86 rows/s
[PID 6532] 180/616 rows | 0.8s elapsed | 215.21 rows/s
[PID 6532] 200/616 rows | 0.9s elapsed | 227.15 rows/s
[PID 6532] 220/616 rows | 0.9s elapsed | 237.94 rows/s
[PID 6532] 240/616 rows | 1.0s elapsed | 246.82 rows/s
[PID 6532] 260/616 rows | 1.0s elapsed | 253.80 rows/s
[PID 6532] 280/616 rows | 1.1s elapsed | 260.89 rows/s
[PID 6532] 300/616 rows | 1.1s elapsed | 267.97 rows/s
[PID 6532] 320/616 rows | 1.2s elapsed | 273.22 rows/s
[PID 6532] 340/616 rows | 1.2s elapsed | 277.26 rows/s
[PID 6532] 360/616 rows | 1.3s elapsed | 280.58 rows/s
[PID 6532] 380/616 rows | 1.3s elapsed | 285.46 rows/s
[PID 6532] 400/616 rows | 1.4s elapsed | 290.36 rows/s
[PID 6532] 420/616 rows | 1.4s elapsed | 293.77 rows/s
[PID 6532] 440/616 rows | 1.5s elapsed | 297.33 rows/s
[PID 6532] 460/616 rows | 1.5s elapsed | 297.78 rows/s
[PID 6532] 480/616 rows | 1.6s elapsed | 301.01 rows/s
[PID 6532] 500/616 rows | 1.6s elapsed | 303.94 rows/s
[PID 6532] 520/616 rows | 1.7s elapsed | 306.85 rows/s
[PID 6532] 540/616 rows | 1.8s elapsed | 308.14 rows/s
[PID 6532] 560/616 rows | 1.8s elapsed | 310.54 rows/s
[PID 6532] 580/616 rows | 1.8s elapsed | 314.57 rows/s
[PID 6532] 600/616 rows | 1.9s elapsed | 316.60 rows/s
[PID 6532] chunk done in 1.9s

Parallel canopy calculation:  15%|█▌        | 3/20 [02:36<15:27, 54.58s/it]

[PID 6533] 20/616 rows | 0.6s elapsed | 33.55 rows/s
[PID 6533] 40/616 rows | 0.7s elapsed | 54.32 rows/s
[PID 6533] 60/616 rows | 0.9s elapsed | 68.78 rows/s
[PID 6533] 80/616 rows | 0.9s elapsed | 86.90 rows/s
[PID 6533] 100/616 rows | 1.0s elapsed | 103.14 rows/s
[PID 6533] 120/616 rows | 1.0s elapsed | 118.40 rows/s
[PID 6533] 140/616 rows | 1.1s elapsed | 129.95 rows/s
[PID 6533] 160/616 rows | 1.2s elapsed | 139.02 rows/s
[PID 6533] 180/616 rows | 1.2s elapsed | 151.09 rows/s
[PID 6533] 200/616 rows | 1.2s elapsed | 165.27 rows/s
[PID 6533] 220/616 rows | 1.2s elapsed | 180.49 rows/s
[PID 6533] 240/616 rows | 1.2s elapsed | 195.24 rows/s
[PID 6533] 260/616 rows | 1.2s elapsed | 209.88 rows/s
[PID 6533] 280/616 rows | 1.3s elapsed | 223.36 rows/s
[PID 6533] 300/616 rows | 1.3s elapsed | 237.65 rows/s
[PID 6533] 320/616 rows | 1.3s elapsed | 248.62 rows/s
[PID 6533] 340/616 rows | 1.3s elapsed | 262.92 rows/s
[PID 6533] 360/616 rows | 1.3s elapsed | 272.46 rows/s
[PID 6533] 380/616 rows | 1.4s elapsed | 274.18 rows/s
[PID 6533] 400/616 rows | 1.4s elapsed | 281.52 rows/s
[PID 6533] 420/616 rows | 1.5s elapsed | 289.16 rows/s
[PID 6533] 440/616 rows | 1.5s elapsed | 296.34 rows/s
[PID 6533] 460/616 rows | 1.5s elapsed | 300.50 rows/s
[PID 6533] 480/616 rows | 1.6s elapsed | 305.04 rows/s
[PID 6533] 500/616 rows | 1.6s elapsed | 309.95 rows/s
[PID 6533] 520/616 rows | 1.6s elapsed | 315.31 rows/s
[PID 6533] 540/616 rows | 1.7s elapsed | 319.23 rows/s
[PID 6533] 560/616 rows | 1.7s elapsed | 325.36 rows/s
[PID 6533] 580/616 rows | 1.8s elapsed | 327.87 rows/s
[PID 6533] 600/616 rows | 1.8s elapsed | 327.06 rows/s
[PID 6533] chunk done in 1.9s

Parallel canopy calculation:  25%|██▌       | 5/20 [05:06<16:57, 67.81s/it]

[PID 6534] 20/616 rows | 1.1s elapsed | 17.80 rows/s
[PID 6534] 40/616 rows | 1.2s elapsed | 32.11 rows/s
[PID 6534] 60/616 rows | 1.4s elapsed | 44.18 rows/s
[PID 6534] 80/616 rows | 1.4s elapsed | 56.91 rows/s
[PID 6534] 100/616 rows | 1.5s elapsed | 68.63 rows/s
[PID 6534] 120/616 rows | 1.5s elapsed | 80.42 rows/s
[PID 6534] 140/616 rows | 1.5s elapsed | 91.32 rows/s
[PID 6534] 160/616 rows | 1.6s elapsed | 101.91 rows/s
[PID 6534] 180/616 rows | 1.6s elapsed | 111.10 rows/s
[PID 6534] 200/616 rows | 1.7s elapsed | 118.50 rows/s
[PID 6534] 220/616 rows | 1.7s elapsed | 126.55 rows/s
[PID 6534] 240/616 rows | 1.8s elapsed | 131.79 rows/s
[PID 6534] 260/616 rows | 1.9s elapsed | 139.92 rows/s
[PID 6534] 280/616 rows | 1.9s elapsed | 144.82 rows/s
[PID 6534] 300/616 rows | 2.0s elapsed | 149.24 rows/s
[PID 6534] 320/616 rows | 2.1s elapsed | 155.46 rows/s
[PID 6534] 340/616 rows | 2.1s elapsed | 161.10 rows/s
[PID 6534] 360/616 rows | 2.1s elapsed | 168.20 rows/s
[PID 6534] 380/616 rows | 2.2s elapsed | 173.96 rows/s
[PID 6534] 400/616 rows | 2.2s elapsed | 179.71 rows/s
[PID 6534] 420/616 rows | 2.3s elapsed | 185.80 rows/s
[PID 6534] 440/616 rows | 2.3s elapsed | 191.19 rows/s
[PID 6534] 460/616 rows | 2.3s elapsed | 196.46 rows/s
[PID 6534] 480/616 rows | 2.4s elapsed | 200.60 rows/s
[PID 6534] 500/616 rows | 2.4s elapsed | 206.35 rows/s
[PID 6534] 520/616 rows | 2.4s elapsed | 212.34 rows/s
[PID 6534] 540/616 rows | 2.5s elapsed | 215.89 rows/s
[PID 6534] 560/616 rows | 2.6s elapsed | 217.95 rows/s
[PID 6534] 580/616 rows | 2.6s elapsed | 221.45 rows/s
[PID 6534] 600/616 rows | 2.7s elapsed | 219.27 rows/s
[PID 6534] chunk done in 2.9s

Parallel canopy calculation:  30%|███       | 6/20 [06:31<17:11, 73.66s/it]

[PID 6535] 20/616 rows | 0.1s elapsed | 201.36 rows/s
[PID 6535] 40/616 rows | 0.2s elapsed | 171.49 rows/s
[PID 6535] 60/616 rows | 0.4s elapsed | 171.18 rows/s
[PID 6535] 80/616 rows | 0.5s elapsed | 165.66 rows/s
[PID 6535] 100/616 rows | 0.6s elapsed | 162.60 rows/s
[PID 6535] 120/616 rows | 0.8s elapsed | 158.22 rows/s
[PID 6535] 140/616 rows | 0.8s elapsed | 178.01 rows/s
[PID 6535] 160/616 rows | 0.8s elapsed | 192.63 rows/s
[PID 6535] 180/616 rows | 0.9s elapsed | 205.05 rows/s
[PID 6535] 200/616 rows | 0.9s elapsed | 213.17 rows/s
[PID 6535] 220/616 rows | 1.0s elapsed | 221.44 rows/s
[PID 6535] 240/616 rows | 1.1s elapsed | 222.94 rows/s
[PID 6535] 260/616 rows | 1.1s elapsed | 226.95 rows/s
[PID 6535] 280/616 rows | 1.2s elapsed | 227.09 rows/s
[PID 6535] 300/616 rows | 1.3s elapsed | 230.26 rows/s
[PID 6535] 320/616 rows | 1.4s elapsed | 232.88 rows/s
[PID 6535] 340/616 rows | 1.4s elapsed | 235.95 rows/s
[PID 6535] 360/616 rows | 1.5s elapsed | 237.31 rows/s
[PID 6535] 380/616 rows | 1.6s elapsed | 239.33 rows/s
[PID 6535] 400/616 rows | 1.7s elapsed | 241.87 rows/s
[PID 6535] 420/616 rows | 1.7s elapsed | 244.27 rows/s
[PID 6535] 440/616 rows | 1.8s elapsed | 246.64 rows/s
[PID 6535] 460/616 rows | 1.8s elapsed | 248.76 rows/s
[PID 6535] 480/616 rows | 1.9s elapsed | 252.45 rows/s
[PID 6535] 500/616 rows | 2.0s elapsed | 255.17 rows/s
[PID 6535] 520/616 rows | 2.0s elapsed | 257.18 rows/s
[PID 6535] 540/616 rows | 2.1s elapsed | 261.22 rows/s
[PID 6535] 560/616 rows | 2.1s elapsed | 265.21 rows/s
[PID 6535] 580/616 rows | 2.2s elapsed | 269.51 rows/s
[PID 6535] 600/616 rows | 2.2s elapsed | 272.40 rows/s
[PID 6535] chunk done in 2.2s
[PID 6536] 20/616 rows | 0.1s elapsed | 148.84 rows/s
[PID 6536] 40/616 rows | 0.2s elapsed | 199.69 rows/s
[PID 6536] 60/616 rows | 0.3s elapsed | 208.87 rows/s
[PID 6536] 80/616 rows | 0.4s elapsed | 210.81 rows/s
[PID 6536] 100/616 rows | 0.5s elapsed | 216.43 rows/s
[PID 6536] 120/616 rows | 0.5s elapsed | 222.78 rows/s
[PID 6536] 140/616 rows | 0.6s elapsed | 228.37 rows/s
[PID 6536] 160/616 rows | 0.7s elapsed | 235.01 rows/s
[PID 6536] 180/616 rows | 0.8s elapsed | 234.55 rows/s
[PID 6536] 200/616 rows | 0.9s elapsed | 235.18 rows/s
[PID 6536] 220/616 rows | 0.9s elapsed | 239.62 rows/s
[PID 6536] 240/616 rows | 1.0s elapsed | 242.23 rows/s
[PID 6536] 260/616 rows | 1.1s elapsed | 245.99 rows/s
[PID 6536] 280/616 rows | 1.1s elapsed | 249.45 rows/s
[PID 6536] 300/616 rows | 1.2s elapsed | 251.50 rows/s
[PID 6536] 320/616 rows | 1.3s elapsed | 253.40 rows/s
[PID 6536] 340/616 rows | 1.3s elapsed | 258.32 rows/s
[PID 6536] 360/616 rows | 1.4s elapsed | 261.86 rows/s
[PID 6536] 380/616 rows | 1.4s elapsed | 264.80 rows/s
[PID 6536] 400/616 rows | 1.5s elapsed | 265.97 rows/s
[PID 6536] 420/616 rows | 1.6s elapsed | 270.64 rows/s
[PID 6536] 440/616 rows | 1.6s elapsed | 279.51 rows/s
[PID 6536] 460/616 rows | 1.6s elapsed | 290.08 rows/s
[PID 6536] 480/616 rows | 1.6s elapsed | 296.64 rows/s
[PID 6536] 500/616 rows | 1.7s elapsed | 302.90 rows/s
[PID 6536] 520/616 rows | 1.7s elapsed | 303.51 rows/s
[PID 6536] 540/616 rows | 1.8s elapsed | 303.21 rows/s
[PID 6536] 560/616 rows | 1.9s elapsed | 302.47 rows/s
[PID 6536] 580/616 rows | 1.9s elapsed | 301.61 rows/s
[PID 6536] 600/616 rows | 2.0s elapsed | 303.42 rows/s
[PID 6536] chunk done in 2.0s

Parallel canopy calculation:  35%|███▌      | 7/20 [07:47<16:08, 74.50s/it]

[PID 6537] 20/616 rows | 0.4s elapsed | 55.05 rows/s
[PID 6537] 40/616 rows | 0.5s elapsed | 88.04 rows/s
[PID 6537] 60/616 rows | 0.6s elapsed | 107.69 rows/s
[PID 6537] 80/616 rows | 0.6s elapsed | 129.96 rows/s
[PID 6537] 100/616 rows | 0.7s elapsed | 145.08 rows/s
[PID 6537] 120/616 rows | 0.7s elapsed | 162.65 rows/s
[PID 6537] 140/616 rows | 0.8s elapsed | 176.77 rows/s
[PID 6537] 160/616 rows | 0.9s elapsed | 183.60 rows/s
[PID 6537] 180/616 rows | 1.0s elapsed | 171.59 rows/s
[PID 6537] 200/616 rows | 1.1s elapsed | 176.95 rows/s
[PID 6537] 220/616 rows | 1.3s elapsed | 172.79 rows/s
[PID 6537] 240/616 rows | 1.3s elapsed | 177.93 rows/s
[PID 6537] 260/616 rows | 1.4s elapsed | 182.13 rows/s
[PID 6537] 280/616 rows | 1.5s elapsed | 181.16 rows/s
[PID 6537] 300/616 rows | 1.6s elapsed | 185.85 rows/s
[PID 6537] 320/616 rows | 1.7s elapsed | 183.94 rows/s
[PID 6537] 340/616 rows | 1.8s elapsed | 187.58 rows/s
[PID 6537] 360/616 rows | 1.9s elapsed | 191.35 rows/s
[PID 6537] 380/616 rows | 2.0s elapsed | 194.56 rows/s
[PID 6537] 400/616 rows | 2.1s elapsed | 193.26 rows/s
[PID 6537] 420/616 rows | 2.2s elapsed | 192.50 rows/s
[PID 6537] 440/616 rows | 2.3s elapsed | 191.26 rows/s
[PID 6537] 460/616 rows | 2.4s elapsed | 190.11 rows/s
[PID 6537] 480/616 rows | 2.5s elapsed | 193.55 rows/s
[PID 6537] 500/616 rows | 2.6s elapsed | 192.35 rows/s
[PID 6537] 520/616 rows | 2.7s elapsed | 192.63 rows/s
[PID 6537] 540/616 rows | 2.8s elapsed | 190.11 rows/s
[PID 6537] 560/616 rows | 2.9s elapsed | 190.28 rows/s
[PID 6537] 580/616 rows | 3.0s elapsed | 191.96 rows/s
[PID 6537] 600/616 rows | 3.1s elapsed | 193.09 rows/s
[PID 6537] chunk done in 3.2s

Parallel canopy calculation:  45%|████▌     | 9/20 [11:01<15:58, 87.13s/it]

[PID 6538] 20/616 rows | 1.1s elapsed | 18.81 rows/s
[PID 6538] 40/616 rows | 1.1s elapsed | 35.58 rows/s
[PID 6538] 60/616 rows | 1.2s elapsed | 50.89 rows/s
[PID 6538] 80/616 rows | 1.2s elapsed | 65.58 rows/s
[PID 6538] 100/616 rows | 1.3s elapsed | 79.36 rows/s
[PID 6538] 120/616 rows | 1.3s elapsed | 92.11 rows/s
[PID 6538] 140/616 rows | 1.3s elapsed | 105.06 rows/s
[PID 6538] 160/616 rows | 1.4s elapsed | 115.92 rows/s
[PID 6538] 180/616 rows | 1.4s elapsed | 124.89 rows/s
[PID 6538] 200/616 rows | 1.5s elapsed | 132.92 rows/s
[PID 6538] 220/616 rows | 1.5s elapsed | 142.71 rows/s
[PID 6538] 240/616 rows | 1.6s elapsed | 151.41 rows/s
[PID 6538] 260/616 rows | 1.6s elapsed | 160.93 rows/s
[PID 6538] 280/616 rows | 1.7s elapsed | 168.13 rows/s
[PID 6538] 300/616 rows | 1.7s elapsed | 174.60 rows/s
[PID 6538] 320/616 rows | 1.8s elapsed | 181.98 rows/s
[PID 6538] 340/616 rows | 1.8s elapsed | 188.03 rows/s
[PID 6538] 360/616 rows | 1.9s elapsed | 194.13 rows/s
[PID 6538] 380/616 rows | 1.9s elapsed | 200.03 rows/s
[PID 6538] 400/616 rows | 2.0s elapsed | 204.62 rows/s
[PID 6538] 420/616 rows | 2.0s elapsed | 210.35 rows/s
[PID 6538] 440/616 rows | 2.0s elapsed | 215.64 rows/s
[PID 6538] 460/616 rows | 2.1s elapsed | 220.96 rows/s
[PID 6538] 480/616 rows | 2.1s elapsed | 226.42 rows/s
[PID 6538] 500/616 rows | 2.2s elapsed | 230.79 rows/s
[PID 6538] 520/616 rows | 2.2s elapsed | 235.93 rows/s
[PID 6538] 540/616 rows | 2.2s elapsed | 241.21 rows/s
[PID 6538] 560/616 rows | 2.3s elapsed | 244.98 rows/s
[PID 6538] 580/616 rows | 2.3s elapsed | 249.49 rows/s
[PID 6538] 600/616 rows | 2.4s elapsed | 254.30 rows/s
[PID 6538] chunk done in 2.4s

Parallel canopy calculation:  50%|█████     | 10/20 [12:14<13:47, 82.79s/it]

[PID 6539] 20/616 rows | 0.2s elapsed | 80.11 rows/s
[PID 6539] 40/616 rows | 0.3s elapsed | 140.44 rows/s
[PID 6539] 60/616 rows | 0.3s elapsed | 185.48 rows/s
[PID 6539] 80/616 rows | 0.4s elapsed | 225.18 rows/s
[PID 6539] 100/616 rows | 0.4s elapsed | 260.80 rows/s
[PID 6539] 120/616 rows | 0.4s elapsed | 283.81 rows/s
[PID 6539] 140/616 rows | 0.5s elapsed | 306.01 rows/s
[PID 6539] 160/616 rows | 0.5s elapsed | 325.30 rows/s
[PID 6539] 180/616 rows | 0.5s elapsed | 339.33 rows/s
[PID 6539] 200/616 rows | 0.6s elapsed | 352.07 rows/s
[PID 6539] 220/616 rows | 0.6s elapsed | 365.63 rows/s
[PID 6539] 240/616 rows | 0.7s elapsed | 366.49 rows/s
[PID 6539] 260/616 rows | 0.7s elapsed | 375.65 rows/s
[PID 6539] 280/616 rows | 0.7s elapsed | 385.64 rows/s
[PID 6539] 300/616 rows | 0.8s elapsed | 395.43 rows/s
[PID 6539] 320/616 rows | 0.8s elapsed | 407.49 rows/s
[PID 6539] 340/616 rows | 0.8s elapsed | 412.36 rows/s
[PID 6539] 360/616 rows | 0.9s elapsed | 418.08 rows/s
[PID 6539] 380/616 rows | 0.9s elapsed | 419.75 rows/s
[PID 6539] 400/616 rows | 0.9s elapsed | 425.21 rows/s
[PID 6539] 420/616 rows | 1.0s elapsed | 420.67 rows/s
[PID 6539] 440/616 rows | 1.0s elapsed | 419.60 rows/s
[PID 6539] 460/616 rows | 1.1s elapsed | 421.46 rows/s
[PID 6539] 480/616 rows | 1.1s elapsed | 424.84 rows/s
[PID 6539] 500/616 rows | 1.2s elapsed | 429.30 rows/s
[PID 6539] 520/616 rows | 1.2s elapsed | 433.94 rows/s
[PID 6539] 540/616 rows | 1.2s elapsed | 436.12 rows/s
[PID 6539] 560/616 rows | 1.3s elapsed | 437.68 rows/s
[PID 6539] 580/616 rows | 1.3s elapsed | 439.40 rows/s
[PID 6539] 600/616 rows | 1.4s elapsed | 444.06 rows/s
[PID 6539] chunk done in 1.4s

Parallel canopy calculation:  55%|█████▌    | 11/20 [13:31<12:08, 80.97s/it]

[PID 6530] 20/616 rows | 0.4s elapsed | 48.17 rows/s
[PID 6530] 40/616 rows | 0.8s elapsed | 48.98 rows/s
[PID 6530] 60/616 rows | 1.1s elapsed | 54.19 rows/s
[PID 6530] 80/616 rows | 1.4s elapsed | 56.97 rows/s
[PID 6530] 100/616 rows | 1.5s elapsed | 64.99 rows/s
[PID 6530] 120/616 rows | 1.7s elapsed | 71.19 rows/s
[PID 6530] 140/616 rows | 1.8s elapsed | 76.94 rows/s
[PID 6530] 160/616 rows | 1.9s elapsed | 82.85 rows/s
[PID 6530] 180/616 rows | 2.0s elapsed | 88.22 rows/s
[PID 6530] 200/616 rows | 2.2s elapsed | 91.87 rows/s
[PID 6530] 220/616 rows | 2.3s elapsed | 95.39 rows/s
[PID 6530] 240/616 rows | 2.4s elapsed | 98.41 rows/s
[PID 6530] 260/616 rows | 2.6s elapsed | 100.20 rows/s
[PID 6530] 280/616 rows | 2.8s elapsed | 101.73 rows/s
[PID 6530] 300/616 rows | 2.8s elapsed | 105.70 rows/s
[PID 6530] 320/616 rows | 3.0s elapsed | 108.21 rows/s
[PID 6530] 340/616 rows | 3.1s elapsed | 110.23 rows/s
[PID 6530] 360/616 rows | 3.2s elapsed | 112.39 rows/s
[PID 6530] 380/616 rows | 3.4s elapsed | 112.68 rows/s
[PID 6530] 400/616 rows | 3.5s elapsed | 114.38 rows/s
[PID 6530] 420/616 rows | 3.6s elapsed | 116.00 rows/s
[PID 6530] 440/616 rows | 3.7s elapsed | 119.76 rows/s
[PID 6530] 460/616 rows | 3.8s elapsed | 122.42 rows/s
[PID 6530] 480/616 rows | 3.8s elapsed | 124.84 rows/s
[PID 6530] 500/616 rows | 4.0s elapsed | 126.25 rows/s
[PID 6530] 520/616 rows | 4.1s elapsed | 127.79 rows/s
[PID 6530] 540/616 rows | 4.2s elapsed | 130.04 rows/s
[PID 6530] 560/616 rows | 4.2s elapsed | 132.14 rows/s
[PID 6530] 580/616 rows | 4.3s elapsed | 134.91 rows/s
[PID 6530] 600/616 rows | 4.4s elapsed | 136.96 rows/s
[PID 6530] chunk done in 4.4s
[PID 6531] 20/616 rows | 0.5s elapsed | 38.40 rows/s
[PID 6531] 40/616 rows | 0.6s elapsed | 66.00 rows/s
[PID 6531] 60/616 rows | 0.7s elapsed | 91.47 rows/s
[PID 6531] 80/616 rows | 0.7s elapsed | 115.25 rows/s
[PID 6531] 100/616 rows | 0.8s elapsed | 118.71 rows/s
[PID 6531] 120/616 rows | 0.9s elapsed | 132.70 rows/s
[PID 6531] 140/616 rows | 0.9s elapsed | 148.71 rows/s
[PID 6531] 160/616 rows | 1.0s elapsed | 161.55 rows/s
[PID 6531] 180/616 rows | 1.1s elapsed | 171.42 rows/s
[PID 6531] 200/616 rows | 1.1s elapsed | 178.94 rows/s
[PID 6531] 220/616 rows | 1.2s elapsed | 188.13 rows/s
[PID 6531] 240/616 rows | 1.2s elapsed | 198.41 rows/s
[PID 6531] 260/616 rows | 1.3s elapsed | 205.05 rows/s
[PID 6531] 280/616 rows | 1.3s elapsed | 212.48 rows/s
[PID 6531] 300/616 rows | 1.4s elapsed | 220.98 rows/s
[PID 6531] 320/616 rows | 1.4s elapsed | 228.83 rows/s
[PID 6531] 340/616 rows | 1.4s elapsed | 235.91 rows/s
[PID 6531] 360/616 rows | 1.5s elapsed | 243.49 rows/s
[PID 6531] 380/616 rows | 1.5s elapsed | 245.75 rows/s
[PID 6531] 400/616 rows | 1.6s elapsed | 250.89 rows/s
[PID 6531] 420/616 rows | 1.6s elapsed | 256.56 rows/s
[PID 6531] 440/616 rows | 1.7s elapsed | 256.81 rows/s
[PID 6531] 460/616 rows | 1.8s elapsed | 260.33 rows/s
[PID 6531] 480/616 rows | 1.8s elapsed | 262.64 rows/s
[PID 6531] 500/616 rows | 1.9s elapsed | 265.56 rows/s
[PID 6531] 520/616 rows | 1.9s elapsed | 268.34 rows/s
[PID 6531] 540/616 rows | 2.0s elapsed | 272.87 rows/s
[PID 6531] 560/616 rows | 2.0s elapsed | 273.65 rows/s
[PID 6531] 580/616 rows | 2.1s elapsed | 277.29 rows/s
[PID 6531] 600/616 rows | 2.1s elapsed | 281.82 rows/s
[PID 6531] chunk done in 2.2s

Parallel canopy calculation:  60%|██████    | 12/20 [14:41<10:20, 77.52s/it]

[PID 6532] 20/616 rows | 0.4s elapsed | 55.85 rows/s
[PID 6532] 40/616 rows | 0.5s elapsed | 88.81 rows/s
[PID 6532] 60/616 rows | 0.6s elapsed | 104.38 rows/s
[PID 6532] 80/616 rows | 0.7s elapsed | 110.46 rows/s
[PID 6532] 100/616 rows | 0.9s elapsed | 116.40 rows/s
[PID 6532] 120/616 rows | 1.0s elapsed | 117.68 rows/s
[PID 6532] 140/616 rows | 1.1s elapsed | 125.89 rows/s
[PID 6532] 160/616 rows | 1.2s elapsed | 132.56 rows/s
[PID 6532] 180/616 rows | 1.4s elapsed | 130.66 rows/s
[PID 6532] 200/616 rows | 1.5s elapsed | 136.54 rows/s
[PID 6532] 220/616 rows | 1.5s elapsed | 141.94 rows/s
[PID 6532] 240/616 rows | 1.6s elapsed | 152.26 rows/s
[PID 6532] 260/616 rows | 1.6s elapsed | 161.87 rows/s
[PID 6532] 280/616 rows | 1.7s elapsed | 168.51 rows/s
[PID 6532] 300/616 rows | 1.7s elapsed | 173.56 rows/s
[PID 6532] 320/616 rows | 1.8s elapsed | 177.73 rows/s
[PID 6532] 340/616 rows | 1.9s elapsed | 180.31 rows/s
[PID 6532] 360/616 rows | 1.9s elapsed | 186.13 rows/s
[PID 6532] 380/616 rows | 2.0s elapsed | 186.90 rows/s
[PID 6532] 400/616 rows | 2.2s elapsed | 184.86 rows/s
[PID 6532] 420/616 rows | 2.3s elapsed | 185.49 rows/s
[PID 6532] 440/616 rows | 2.4s elapsed | 186.61 rows/s
[PID 6532] 460/616 rows | 2.4s elapsed | 191.17 rows/s
[PID 6532] 480/616 rows | 2.5s elapsed | 193.11 rows/s
[PID 6532] 500/616 rows | 2.5s elapsed | 197.23 rows/s
[PID 6532] 520/616 rows | 2.6s elapsed | 201.45 rows/s
[PID 6532] 540/616 rows | 2.6s elapsed | 204.23 rows/s
[PID 6532] 560/616 rows | 2.8s elapsed | 201.66 rows/s
[PID 6532] 580/616 rows | 2.9s elapsed | 203.45 rows/s
[PID 6532] 600/616 rows | 2.9s elapsed | 205.86 rows/s
[PID 6532] chunk done in 3.0s

Parallel canopy calculation:  65%|██████▌   | 13/20 [16:13<09:33, 81.89s/it]

[PID 6533] 20/616 rows | 0.3s elapsed | 79.65 rows/s
[PID 6533] 40/616 rows | 0.3s elapsed | 131.93 rows/s
[PID 6533] 60/616 rows | 0.3s elapsed | 173.99 rows/s
[PID 6533] 80/616 rows | 0.4s elapsed | 204.92 rows/s
[PID 6533] 100/616 rows | 0.4s elapsed | 233.76 rows/s
[PID 6533] 120/616 rows | 0.5s elapsed | 261.79 rows/s
[PID 6533] 140/616 rows | 0.6s elapsed | 252.37 rows/s
[PID 6533] 160/616 rows | 0.6s elapsed | 267.20 rows/s
[PID 6533] 180/616 rows | 0.6s elapsed | 282.08 rows/s
[PID 6533] 200/616 rows | 0.7s elapsed | 285.10 rows/s
[PID 6533] 220/616 rows | 0.7s elapsed | 297.00 rows/s
[PID 6533] 240/616 rows | 0.8s elapsed | 302.46 rows/s
[PID 6533] 260/616 rows | 0.8s elapsed | 313.40 rows/s
[PID 6533] 280/616 rows | 0.9s elapsed | 322.88 rows/s
[PID 6533] 300/616 rows | 0.9s elapsed | 335.17 rows/s
[PID 6533] 320/616 rows | 0.9s elapsed | 341.35 rows/s
[PID 6533] 340/616 rows | 1.0s elapsed | 351.73 rows/s
[PID 6533] 360/616 rows | 1.0s elapsed | 361.18 rows/s
[PID 6533] 380/616 rows | 1.0s elapsed | 366.77 rows/s
[PID 6533] 400/616 rows | 1.1s elapsed | 370.47 rows/s
[PID 6533] 420/616 rows | 1.1s elapsed | 377.49 rows/s
[PID 6533] 440/616 rows | 1.2s elapsed | 378.40 rows/s
[PID 6533] 460/616 rows | 1.2s elapsed | 378.86 rows/s
[PID 6533] 480/616 rows | 1.3s elapsed | 380.57 rows/s
[PID 6533] 500/616 rows | 1.3s elapsed | 386.08 rows/s
[PID 6533] 520/616 rows | 1.3s elapsed | 392.08 rows/s
[PID 6533] 540/616 rows | 1.4s elapsed | 397.28 rows/s
[PID 6533] 560/616 rows | 1.4s elapsed | 403.40 rows/s
[PID 6533] 580/616 rows | 1.4s elapsed | 408.83 rows/s
[PID 6533] 600/616 rows | 1.5s elapsed | 412.59 rows/s
[PID 6533] chunk done in 1.5s

Parallel canopy calculation:  70%|███████   | 14/20 [17:35<08:12, 82.01s/it]

[PID 6534] 20/616 rows | 0.7s elapsed | 29.02 rows/s
[PID 6534] 40/616 rows | 0.7s elapsed | 54.32 rows/s
[PID 6534] 60/616 rows | 0.8s elapsed | 77.77 rows/s
[PID 6534] 80/616 rows | 0.8s elapsed | 100.04 rows/s
[PID 6534] 100/616 rows | 0.9s elapsed | 116.54 rows/s
[PID 6534] 120/616 rows | 0.9s elapsed | 135.57 rows/s
[PID 6534] 140/616 rows | 0.9s elapsed | 154.00 rows/s
[PID 6534] 160/616 rows | 0.9s elapsed | 168.97 rows/s
[PID 6534] 180/616 rows | 1.0s elapsed | 181.90 rows/s
[PID 6534] 200/616 rows | 1.0s elapsed | 196.00 rows/s
[PID 6534] 220/616 rows | 1.1s elapsed | 208.24 rows/s
[PID 6534] 240/616 rows | 1.1s elapsed | 217.34 rows/s
[PID 6534] 260/616 rows | 1.2s elapsed | 224.46 rows/s
[PID 6534] 280/616 rows | 1.2s elapsed | 228.57 rows/s
[PID 6534] 300/616 rows | 1.3s elapsed | 233.14 rows/s
[PID 6534] 320/616 rows | 1.3s elapsed | 238.27 rows/s
[PID 6534] 340/616 rows | 1.4s elapsed | 242.13 rows/s
[PID 6534] 360/616 rows | 1.5s elapsed | 247.79 rows/s
[PID 6534] 380/616 rows | 1.5s elapsed | 258.81 rows/s
[PID 6534] 400/616 rows | 1.5s elapsed | 268.57 rows/s
[PID 6534] 420/616 rows | 1.5s elapsed | 277.43 rows/s
[PID 6534] 440/616 rows | 1.5s elapsed | 284.53 rows/s
[PID 6534] 460/616 rows | 1.6s elapsed | 290.41 rows/s
[PID 6534] 480/616 rows | 1.6s elapsed | 296.61 rows/s
[PID 6534] 500/616 rows | 1.7s elapsed | 302.15 rows/s
[PID 6534] 520/616 rows | 1.7s elapsed | 305.36 rows/s
[PID 6534] 540/616 rows | 1.8s elapsed | 304.93 rows/s
[PID 6534] 560/616 rows | 1.8s elapsed | 308.22 rows/s
[PID 6534] 580/616 rows | 1.8s elapsed | 314.34 rows/s
[PID 6534] 600/616 rows | 1.9s elapsed | 318.81 rows/s
[PID 6534] chunk done in 1.9s

Parallel canopy calculation:  75%|███████▌  | 15/20 [19:07<07:04, 84.91s/it]

[PID 6535] 20/616 rows | 0.3s elapsed | 58.72 rows/s
[PID 6535] 40/616 rows | 0.4s elapsed | 107.49 rows/s
[PID 6535] 60/616 rows | 0.5s elapsed | 123.36 rows/s
[PID 6535] 80/616 rows | 0.5s elapsed | 146.21 rows/s
[PID 6535] 100/616 rows | 0.6s elapsed | 166.72 rows/s
[PID 6535] 120/616 rows | 0.7s elapsed | 181.85 rows/s
[PID 6535] 140/616 rows | 0.7s elapsed | 192.57 rows/s
[PID 6535] 160/616 rows | 0.7s elapsed | 214.00 rows/s
[PID 6535] 180/616 rows | 0.8s elapsed | 230.81 rows/s
[PID 6535] 200/616 rows | 0.8s elapsed | 247.55 rows/s
[PID 6535] 220/616 rows | 0.8s elapsed | 262.08 rows/s
[PID 6535] 240/616 rows | 0.9s elapsed | 271.46 rows/s
[PID 6535] 260/616 rows | 0.9s elapsed | 278.88 rows/s
[PID 6535] 280/616 rows | 1.0s elapsed | 291.88 rows/s
[PID 6535] 300/616 rows | 1.0s elapsed | 300.16 rows/s
[PID 6535] 320/616 rows | 1.0s elapsed | 310.44 rows/s
[PID 6535] 340/616 rows | 1.1s elapsed | 317.73 rows/s
[PID 6535] 360/616 rows | 1.1s elapsed | 324.14 rows/s
[PID 6535] 380/616 rows | 1.1s elapsed | 332.02 rows/s
[PID 6535] 400/616 rows | 1.2s elapsed | 335.19 rows/s
[PID 6535] 420/616 rows | 1.2s elapsed | 338.44 rows/s
[PID 6535] 440/616 rows | 1.3s elapsed | 346.24 rows/s
[PID 6535] 460/616 rows | 1.3s elapsed | 354.58 rows/s
[PID 6535] 480/616 rows | 1.3s elapsed | 364.76 rows/s
[PID 6535] 500/616 rows | 1.3s elapsed | 372.21 rows/s
[PID 6535] 520/616 rows | 1.4s elapsed | 380.09 rows/s
[PID 6535] 540/616 rows | 1.4s elapsed | 386.17 rows/s
[PID 6535] 560/616 rows | 1.4s elapsed | 392.78 rows/s
[PID 6535] 580/616 rows | 1.5s elapsed | 398.50 rows/s
[PID 6535] 600/616 rows | 1.5s elapsed | 404.74 rows/s
[PID 6535] chunk done in 1.5s

Parallel canopy calculation:  80%|████████  | 16/20 [20:23<05:29, 82.36s/it]

[PID 6536] 20/616 rows | 0.3s elapsed | 68.70 rows/s
[PID 6536] 40/616 rows | 0.5s elapsed | 79.36 rows/s
[PID 6536] 60/616 rows | 0.6s elapsed | 94.80 rows/s
[PID 6536] 80/616 rows | 0.7s elapsed | 112.54 rows/s
[PID 6536] 100/616 rows | 0.7s elapsed | 133.99 rows/s
[PID 6536] 120/616 rows | 0.8s elapsed | 153.64 rows/s
[PID 6536] 140/616 rows | 0.8s elapsed | 166.55 rows/s
[PID 6536] 160/616 rows | 0.9s elapsed | 181.14 rows/s
[PID 6536] 180/616 rows | 0.9s elapsed | 196.97 rows/s
[PID 6536] 200/616 rows | 0.9s elapsed | 210.76 rows/s
[PID 6536] 220/616 rows | 1.0s elapsed | 226.44 rows/s
[PID 6536] 240/616 rows | 1.0s elapsed | 237.22 rows/s
[PID 6536] 260/616 rows | 1.0s elapsed | 251.77 rows/s
[PID 6536] 280/616 rows | 1.1s elapsed | 259.43 rows/s
[PID 6536] 300/616 rows | 1.1s elapsed | 270.34 rows/s
[PID 6536] 320/616 rows | 1.1s elapsed | 279.85 rows/s
[PID 6536] 340/616 rows | 1.2s elapsed | 287.29 rows/s
[PID 6536] 360/616 rows | 1.2s elapsed | 297.40 rows/s
[PID 6536] 380/616 rows | 1.2s elapsed | 307.60 rows/s
[PID 6536] 400/616 rows | 1.3s elapsed | 319.03 rows/s
[PID 6536] 420/616 rows | 1.3s elapsed | 330.50 rows/s
[PID 6536] 440/616 rows | 1.3s elapsed | 337.80 rows/s
[PID 6536] 460/616 rows | 1.3s elapsed | 343.94 rows/s
[PID 6536] 480/616 rows | 1.4s elapsed | 350.26 rows/s
[PID 6536] 500/616 rows | 1.4s elapsed | 351.33 rows/s
[PID 6536] 520/616 rows | 1.5s elapsed | 358.31 rows/s
[PID 6536] 540/616 rows | 1.5s elapsed | 366.82 rows/s
[PID 6536] 560/616 rows | 1.5s elapsed | 377.87 rows/s
[PID 6536] 580/616 rows | 1.5s elapsed | 386.63 rows/s
[PID 6536] 600/616 rows | 1.5s elapsed | 391.17 rows/s
[PID 6536] chunk done in 1.6s

Parallel canopy calculation:  90%|█████████ | 18/20 [23:33<02:55, 87.81s/it]

[PID 6537] 20/615 rows | 0.5s elapsed | 40.69 rows/s
[PID 6537] 40/615 rows | 0.5s elapsed | 74.68 rows/s
[PID 6537] 60/615 rows | 0.6s elapsed | 106.22 rows/s
[PID 6537] 80/615 rows | 0.6s elapsed | 134.84 rows/s
[PID 6537] 100/615 rows | 0.6s elapsed | 161.07 rows/s
[PID 6537] 120/615 rows | 0.6s elapsed | 186.25 rows/s
[PID 6537] 140/615 rows | 0.7s elapsed | 210.62 rows/s
[PID 6537] 160/615 rows | 0.7s elapsed | 230.07 rows/s
[PID 6537] 180/615 rows | 0.7s elapsed | 249.96 rows/s
[PID 6537] 200/615 rows | 0.8s elapsed | 266.34 rows/s
[PID 6537] 220/615 rows | 0.8s elapsed | 285.75 rows/s
[PID 6537] 240/615 rows | 0.8s elapsed | 301.15 rows/s
[PID 6537] 260/615 rows | 0.8s elapsed | 319.82 rows/s
[PID 6537] 280/615 rows | 0.9s elapsed | 325.75 rows/s
[PID 6537] 300/615 rows | 0.9s elapsed | 343.78 rows/s
[PID 6537] 320/615 rows | 0.9s elapsed | 356.08 rows/s
[PID 6537] 340/615 rows | 0.9s elapsed | 375.20 rows/s
[PID 6537] 360/615 rows | 0.9s elapsed | 387.62 rows/s
[PID 6537] 380/615 rows | 0.9s elapsed | 405.27 rows/s
[PID 6537] 400/615 rows | 0.9s elapsed | 421.10 rows/s
[PID 6537] 420/615 rows | 1.0s elapsed | 431.87 rows/s
[PID 6537] 440/615 rows | 1.0s elapsed | 440.03 rows/s
[PID 6537] 460/615 rows | 1.0s elapsed | 447.72 rows/s
[PID 6537] 480/615 rows | 1.1s elapsed | 455.28 rows/s
[PID 6537] 500/615 rows | 1.1s elapsed | 464.00 rows/s
[PID 6537] 520/615 rows | 1.1s elapsed | 470.40 rows/s
[PID 6537] 540/615 rows | 1.1s elapsed | 478.63 rows/s
[PID 6537] 560/615 rows | 1.2s elapsed | 485.42 rows/s
[PID 6537] 580/615 rows | 1.2s elapsed | 488.40 rows/s
[PID 6537] 600/615 rows | 1.2s elapsed | 496.62 rows/s
[PID 6537] chunk done in 1.2s
[PID 6538] 20/615 rows | 0.4s elapsed | 50.68 rows/s
[PID 6538] 40/615 rows | 0.4s elapsed | 92.31 rows/s
[PID 6538] 60/615 rows | 0.5s elapsed | 125.84 rows/s
[PID 6538] 80/615 rows | 0.6s elapsed | 140.33 rows/s
[PID 6538] 100/615 rows | 0.6s elapsed | 159.43 rows/s
[PID 6538] 120/615 rows | 0.7s elapsed | 179.45 rows/s
[PID 6538] 140/615 rows | 0.7s elapsed | 193.97 rows/s
[PID 6538] 160/615 rows | 0.8s elapsed | 199.95 rows/s
[PID 6538] 180/615 rows | 0.9s elapsed | 202.95 rows/s
[PID 6538] 200/615 rows | 0.9s elapsed | 211.55 rows/s
[PID 6538] 220/615 rows | 1.0s elapsed | 221.67 rows/s
[PID 6538] 240/615 rows | 1.1s elapsed | 225.81 rows/s
[PID 6538] 260/615 rows | 1.1s elapsed | 230.68 rows/s
[PID 6538] 280/615 rows | 1.2s elapsed | 235.78 rows/s
[PID 6538] 300/615 rows | 1.3s elapsed | 235.57 rows/s
[PID 6538] 320/615 rows | 1.3s elapsed | 238.02 rows/s
[PID 6538] 340/615 rows | 1.4s elapsed | 241.05 rows/s
[PID 6538] 360/615 rows | 1.5s elapsed | 246.98 rows/s
[PID 6538] 380/615 rows | 1.5s elapsed | 251.48 rows/s
[PID 6538] 400/615 rows | 1.6s elapsed | 257.19 rows/s
[PID 6538] 420/615 rows | 1.6s elapsed | 264.48 rows/s
[PID 6538] 440/615 rows | 1.6s elapsed | 271.46 rows/s
[PID 6538] 460/615 rows | 1.7s elapsed | 278.61 rows/s
[PID 6538] 480/615 rows | 1.7s elapsed | 282.64 rows/s
[PID 6538] 500/615 rows | 1.7s elapsed | 288.74 rows/s
[PID 6538] 520/615 rows | 1.8s elapsed | 295.38 rows/s
[PID 6538] 540/615 rows | 1.8s elapsed | 301.09 rows/s
[PID 6538] 560/615 rows | 1.8s elapsed | 305.70 rows/s
[PID 6538] 580/615 rows | 1.9s elapsed | 308.69 rows/s
[PID 6538] 600/615 rows | 1.9s elapsed | 312.66 rows/s
[PID 6538] chunk done in 2.0s

Parallel canopy calculation:  95%|█████████▌| 19/20 [24:58<01:27, 87.13s/it]

[PID 6539] 20/615 rows | 0.6s elapsed | 34.43 rows/s
[PID 6539] 40/615 rows | 0.7s elapsed | 61.53 rows/s
[PID 6539] 60/615 rows | 0.7s elapsed | 86.96 rows/s
[PID 6539] 80/615 rows | 0.7s elapsed | 110.57 rows/s
[PID 6539] 100/615 rows | 0.8s elapsed | 132.28 rows/s
[PID 6539] 120/615 rows | 0.8s elapsed | 153.29 rows/s
[PID 6539] 140/615 rows | 0.8s elapsed | 172.41 rows/s
[PID 6539] 160/615 rows | 0.8s elapsed | 188.75 rows/s
[PID 6539] 180/615 rows | 0.9s elapsed | 204.44 rows/s
[PID 6539] 200/615 rows | 0.9s elapsed | 217.99 rows/s
[PID 6539] 220/615 rows | 1.0s elapsed | 230.13 rows/s
[PID 6539] 240/615 rows | 1.0s elapsed | 240.27 rows/s
[PID 6539] 260/615 rows | 1.0s elapsed | 252.59 rows/s
[PID 6539] 280/615 rows | 1.1s elapsed | 261.67 rows/s
[PID 6539] 300/615 rows | 1.1s elapsed | 270.05 rows/s
[PID 6539] 320/615 rows | 1.1s elapsed | 281.79 rows/s
[PID 6539] 340/615 rows | 1.2s elapsed | 290.10 rows/s
[PID 6539] 360/615 rows | 1.2s elapsed | 299.19 rows/s
[PID 6539] 380/615 rows | 1.2s elapsed | 308.21 rows/s
[PID 6539] 400/615 rows | 1.3s elapsed | 318.00 rows/s
[PID 6539] 420/615 rows | 1.3s elapsed | 331.86 rows/s
[PID 6539] 440/615 rows | 1.3s elapsed | 344.80 rows/s
[PID 6539] 460/615 rows | 1.3s elapsed | 357.75 rows/s
[PID 6539] 480/615 rows | 1.3s elapsed | 362.89 rows/s
[PID 6539] 500/615 rows | 1.4s elapsed | 367.35 rows/s
[PID 6539] 520/615 rows | 1.4s elapsed | 373.38 rows/s
[PID 6539] 540/615 rows | 1.4s elapsed | 375.40 rows/s
[PID 6539] 560/615 rows | 1.5s elapsed | 378.66 rows/s
[PID 6539] 580/615 rows | 1.5s elapsed | 382.73 rows/s
[PID 6539] 600/615 rows | 1.5s elapsed | 388.50 rows/s
[PID 6539] chunk done in 1.6s

Parallel canopy calculation: 100%|██████████| 20/20 [25:42<00:00, 77.12s/it]

In [6]:
for chunk_result in results:
    for idx, res in chunk_result:
        if res is None:
            continue
        for key, value in res.items():
            property_reaches.at[idx, key] = value

In [7]:
# reaches = [50, 100, 150, 200, 250, 300, 350, 400]
reaches = [75]

canopy_cols = [f"canopy_{d}m" for d in reaches]

canopy_out = property_reaches[canopy_cols].copy()

canopy_out["property_id"] = property_reaches.index

canopy_out = canopy_out[["property_id"] + canopy_cols]

canopy_out = gpd.GeoDataFrame(
    canopy_out,
    geometry=property_reaches.geometry,
    crs=property_reaches.crs
)

In [8]:
canopy_out.head()

   property_id  canopy_75m                         geometry
0            0   71.199176  POINT (1564919.129 5174157.305)
1            1   39.233007   POINT (1565047.92 5174178.753)
2            2  153.781247  POINT (1564904.931 5174179.536)
3            3   32.559216  POINT (1565029.188 5174201.753)
4            4  162.647867  POINT (1564988.184 5174211.698)

In [9]:
out_path = "output/property_isodistance_canopies_75.gpkg"

canopy_out.to_file(
    out_path,
    layer="canopy_by_reach",
    driver="GPKG",
    engine="pyogrio"
)

In [10]:
canopy_out.shape

(12317, 3)

In [11]:
canopy_out.head()

   property_id  canopy_75m                         geometry
0            0   71.199176  POINT (1564919.129 5174157.305)
1            1   39.233007   POINT (1565047.92 5174178.753)
2            2  153.781247  POINT (1564904.931 5174179.536)
3            3   32.559216  POINT (1565029.188 5174201.753)
4            4  162.647867  POINT (1564988.184 5174211.698)

# combine all canopy files

In [12]:
property_wo_75 = gpd.read_file('output/property_isodistance_canopies.gpkg')

In [13]:
print(canopy_out.shape)
print(property_wo_75.shape)

(12317, 3)
(12317, 11)

In [14]:
property_canopies_full = property_wo_75.merge(
  canopy_out[['property_id', 'canopy_75m']],
  how='left',
  on='property_id'
)

In [15]:
property_canopies_full.shape

(12317, 12)

In [16]:
property_canopies_full.head()

,property_id,canopy_50m,canopy_100m,canopy_150m,canopy_200m,canopy_250m,canopy_300m,canopy_350m,canopy_400m,canopy_25m,geometry,canopy_75m
0,0,25.782986,192.711307,204.768643,319.550849,550.032059,682.414635,932.266395,1242.955144,14.466409,POINT (1564919.129 5174157.305),71.199176
1,1,30.495473,116.039225,369.255412,501.136692,852.088438,1146.041794,1603.443922,2132.706457,27.566893,POINT (1565047.92 5174178.753),39.233007
2,2,146.128014,161.708964,190.194919,204.768643,251.751149,496.983665,679.576348,856.535574,32.582817,POINT (1564904.931 5174179.536),153.781247
3,3,30.495473,165.048229,353.665378,511.542446,909.228096,1135.821806,1627.178436,2312.325189,0.000000,POINT (1565029.188 5174201.753),32.559216
4,4,42.975251,188.162874,194.655967,222.928693,385.847184,632.951004,767.283211,1057.061872,9.263134,POINT (1564988.184 5174211.698),162.647867

In [17]:
property_canopies_full.to_file(
    'output/property_isodistance_canopies.gpkg',
    layer="canopy_by_reach",
    driver="GPKG",
    engine="pyogrio"
)